Django/firstweb/firstweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("vicpay.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
    path('todo/', include("todo.urls"))

    
]

Django/firstweb/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

Django/firstweb/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
   path("", views.index, name="index"),
   path("add",views.add, name="add")
   
]

Django/firstweb/todo/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

Django/firstweb/vicpay/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("pay", views.pay, name="pay" ),
    path("<str:name>", views.greet, name="greet")
]

Django/firstweb/newyear/models.py
from django.db import models

# Create your models here.

Django/firstweb/tasks/models.py
from django.db import models

# Create your models here.

Django/firstweb/todo/models.py
from django.db import models

# Create your models here.

Django/firstweb/vicpay/models.py
from django.db import models

# Create your models here.

Django/firstweb/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
       "newyear": now.month == 1 and now.day == 1 
    })

Django/firstweb/tasks/views.py
from django.shortcuts import render
from django import forms

tasks = ["Alx", "CS50", "God"]

class Newtaskform(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label = "numbers", min_value=1, max_value=10)



# Create your views here.
def index(request):
    return render(request, "tasks/index.html",{
        "tasks": tasks
    })
def add(request):
    return render(request, "tasks/add.html",{
        "form": Newtaskform()
    })

Django/firstweb/todo/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
     return render(request, "todo/index.html")


def add(request):
    return render(request, "todo/add.html")

Django/firstweb/vicpay/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"vicpay/index.html")

def pay(request):
    return HttpResponse("select payment method")

def greet(request,name):
    return render(request, "vicpay/greet.html", {
        "name": name.capitalize()
    })

Django/firstweb/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newyear</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
    <style>

    </style>
</head>
<body>
    {% if newyear %}
        <h1 style="text-align: center;">YES</h1>
    {% else %}
        <h1 style="text-align: center;">NO</h1>
    {% endif %}
</body>
</html>

Django/firstweb/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}


{% block body %}
    <h1>Add new tasks</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
       <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">Add a new task</a>
{% endblock %}

Django/firstweb/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}


{% block body %}
    <ul>
       {% for tasks in tasks %}
            <li>{{tasks}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

Django/firstweb/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

Django/firstweb/todo/templates/todo/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello world</h1>
</body>
</html>

Django/firstweb/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>fuck it</h1>
</body>
</html>

Django/firstweb/vicpay/templates/vicpay/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello , {{name}}</h1>
</body>
</html>

Django/firstweb/vicpay/templates/vicpay/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello people </h1>
</body>
</html>